version: "3"


services:
  Mysqlcontaine:
     container_name: mysql 
     image: mysql
     environment:
      MYSQL_ROOT_HOST: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: major
      MYSQL_USER: sa
      MYSQL_PASSWORD: 1234  
     ports:
       - '3307:3306'
  springcontainer:
     build:
      dockerfile: Dockerfile
      context: ./
     ports:
       - '9999:8080'
     environment:
       MYSQL_HOST: mysql
       MYSQL_USER: root
       MYSQL_PASSWORD: 1234   
     depends_on:
       - 'Mysqlcontaine'  
     volumes:
       - ./src:/usr/local/src
     
        
     
     
    
       