spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_healthcard
    username: root
    password: root
  
secretkey: healthcard
spring.application.name: HealthCard Server    
    
    
    
    
    